# Generated by Django 5.0.7 on 2024-07-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.ImageField(blank=True, null=True, upload_to='')),
                ('Brand_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('CategoryImage1', models.ImageField(blank=True, null=True, upload_to='product images')),
                ('CategoryImage2', models.ImageField(blank=True, null=True, upload_to='product images')),
                ('CategoryImage3', models.ImageField(blank=True, null=True, upload_to='product images')),
            ],
        ),
    ]
